// vms/frontend-str-angular/src/app/app.component.ts
import { Component, computed, effect, inject, signal } from '@angular/core'
import { CommonModule } from '@angular/common'
import { DomSanitizer, SafeHtml, SafeResourceUrl, SafeUrl } from '@angular/platform-browser'
import { authors as AUTHORS, posts as POSTS, getComments, addComment } from './data'
import { CstiPreviewComponent } from './csti-preview.component'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, CstiPreviewComponent],
  template: `
    <nav>
      <span class="brand">DevBlog · angular</span>
      <a href="#/">Home</a>
      <a href="#/compose">Compose</a>
      <a href="#/profile/ada">Profile</a>
    </nav>

    <div class="container">
      <!-- Home -->
      <div class="layout" *ngIf="isHome()">
        <main>
          <h1>Latest posts</h1>
          <div class="teaser" *ngFor="let p of posts">
            <a [href]="'#/post/' + p.id"><h2>{{ p.title }}</h2></a>
            <p class="byline">by {{ authors[p.author].name }}</p>
          </div>
        </main>
        <aside>
          <h3>Widget</h3>
          <div [class]="widget() === 'admin' ? 'widget admin' : 'widget'">{{ widgetText() }}</div>
          <p class="hint">try <code>#/?widget=admin</code></p>
        </aside>
      </div>

      <!-- Post -->
      <article *ngIf="isPost()">
        <ng-container *ngIf="post() as po">
          <h1>{{ po.title }}</h1>
          <p class="byline">
            by {{ postAuthor()?.name }} —
            <a class="author-link" [href]="trustUrl(postAuthor()!.website)">{{ postAuthor()!.name }}'s site ↗</a>
          </p>
          <div class="body" [innerHTML]="trustHtml(po.body)"></div>
          <section class="comments">
            <h3>Comments</h3>
            <p class="muted" *ngIf="comments().length === 0">No comments yet.</p>
            <div class="comment" *ngFor="let c of comments()" [innerHTML]="trustHtml(c.body)"></div>
            <textarea
              [value]="draft()"
              (input)="draft.set($event.target.value)"
              placeholder="Add a comment (HTML allowed)…"
            ></textarea>
            <button (click)="submitComment()">Post comment</button>
          </section>
        </ng-container>
        <p *ngIf="!post()">Post not found.</p>
      </article>

      <!-- Compose -->
      <div *ngIf="isCompose()">
        <h1>Compose</h1>

        <label>Body (HTML) — trusted via bypassSecurityTrustHtml</label>
        <textarea [value]="composeHtml()" (input)="composeHtml.set($event.target.value)"></textarea>
        <h3>Live preview (bypassed → raw)</h3>
        <div class="body" [innerHTML]="trustHtml(composeHtml())"></div>

        <h3>Same input via plain [innerHTML] (Angular sanitizes → script stripped)</h3>
        <div class="body" [innerHTML]="composeHtml()"></div>

        <label>Template preview (compiled at runtime — CSTI)</label>
        <input [value]="tpl()" (input)="tpl.set($event.target.value)" />
        <csti-preview [tpl]="tpl()"></csti-preview>
        <p class="hint">CSTI try: <code>{{ cstiHint }}</code></p>

        <label>Embed URL — trusted via bypassSecurityTrustResourceUrl</label>
        <input [value]="embedUrl()" (input)="embedUrl.set($event.target.value)" placeholder="https://…" />
        <iframe class="embed" *ngIf="embedUrl()" [src]="trustResource(embedUrl())" title="embed"></iframe>

        <label>Redirect (?next=) — open redirect</label>
        <input [value]="redirectUrl()" (input)="redirectUrl.set($event.target.value)" placeholder="https://… or javascript:…" />
        <button (click)="redirect(redirectUrl())">Continue</button>
      </div>

      <!-- Profile -->
      <div *ngIf="isProfile()">
        <ng-container *ngIf="profileAuthor() as a">
          <h1>{{ a.name }}</h1>
          <div class="body" [innerHTML]="trustHtml(a.bio)"></div>
          <p><a class="author-link" [href]="trustUrl(a.website)">{{ a.name }}'s site ↗</a></p>
          <p class="hint">try <code>#/profile/ada?url=javascript:alert(document.domain)</code></p>
        </ng-container>
        <p *ngIf="!profileAuthor()">No such author.</p>
      </div>
    </div>
  `,
})
export class AppComponent {
  private san = inject(DomSanitizer)

  authors = AUTHORS
  posts = POSTS
  cstiHint = "{{constructor.constructor('alert(1)')()}}"

  hash = signal(location.hash || '#/')
  comments = signal<{ body: string; at: number }[]>([])
  draft = signal('')
  composeHtml = signal('<h2>Draft</h2><p>Type some HTML…</p>')
  embedUrl = signal('')
  redirectUrl = signal('')
  tpl = signal('Hello {{ 1 + 1 }}')

  constructor() {
    addEventListener('hashchange', () => this.hash.set(location.hash || '#/'))
    // Refresh stored comments whenever we view a post.
    effect(() => {
      if (this.path().startsWith('/post/')) this.comments.set(getComments(this.postId()))
    })
    // Prefill the redirect box from ?next= so the open-redirect sink is reachable.
    effect(() => {
      const n = this.query().get('next')
      if (n) this.redirectUrl.set(n)
    })
  }

  query = computed(() => {
    const h = this.hash()
    const i = h.indexOf('?')
    return new URLSearchParams(i >= 0 ? h.slice(i + 1) : '')
  })
  path = computed(() => this.hash().replace(/^#/, '').split('?')[0])

  isHome = computed(() => this.path() === '/' || this.path() === '')
  isPost = computed(() => this.path().startsWith('/post/'))
  isCompose = computed(() => this.path().startsWith('/compose'))
  isProfile = computed(() => this.path().startsWith('/profile/'))

  widget = computed(() => this.query().get('widget') || 'hello')
  widgetText = computed(() => {
    const m: Record<string, string> = {
      hello: '👋 Hello, reader!',
      stats: '1,024 readers online',
      admin: 'ADMIN · build token = devblog-ci-7f3a-do-not-share',
    }
    return m[this.widget()] || m['hello']
  })

  postId = computed(() => Number(this.path().split('/')[2]))
  post = computed(() => POSTS.find((p) => p.id === this.postId()))
  postAuthor = computed(() => {
    const p = this.post()
    return p ? AUTHORS[p.author] : null
  })

  profileAuthor = computed(() => {
    const a = AUTHORS[this.path().split('/')[2]]
    if (!a) return null
    return {
      ...a,
      website: this.query().get('url') || a.website,
      bio: this.query().get('bio') || a.bio,
    }
  })

  submitComment() {
    addComment(this.postId(), this.draft())
    this.draft.set('')
    this.comments.set(getComments(this.postId()))
  }

  // VULN[ng-bypass-html] — [innerHTML] is auto-sanitized by Angular; calling
  // bypassSecurityTrustHtml disables that, so the markup renders raw.
  trustHtml = (h: string): SafeHtml => this.san.bypassSecurityTrustHtml(h)

  // VULN[ng-bypass-url] — [href] is auto-sanitized (javascript: stripped);
  // bypassSecurityTrustUrl re-enables dangerous schemes.
  trustUrl = (u: string): SafeUrl => this.san.bypassSecurityTrustUrl(u)

  // VULN[ng-bypass-resourceurl] — resource URLs (iframe/script src) are
  // normally blocked unless trusted; this trusts arbitrary origins.
  trustResource = (u: string): SafeResourceUrl => this.san.bypassSecurityTrustResourceUrl(u)

  // VULN[ng-open-redirect] — navigates to a fully user-controlled location.
  redirect(u: string) {
    if (u) location.href = u
  }
}

// vms/frontend-str-vue/src/App.vue
<script setup>
import { ref, computed, watchEffect, onMounted, onUnmounted } from 'vue'
import { posts, authors, getComments, addComment } from './data.js'
import { PostBody, AuthorLink, Embed, widgets } from './components.js'

const hash = ref(window.location.hash || '#/')
const onHash = () => { hash.value = window.location.hash || '#/' }
onMounted(() => window.addEventListener('hashchange', onHash))
onUnmounted(() => window.removeEventListener('hashchange', onHash))

const query = computed(() => {
  const i = hash.value.indexOf('?')
  return new URLSearchParams(i >= 0 ? hash.value.slice(i + 1) : '')
})
const path = computed(() => hash.value.replace(/^#/, '').split('?')[0])

// Home / widget
const widget = computed(() => widgets[query.value.get('widget')] || widgets.hello)

// Post view
const postId = computed(() => Number(path.value.split('/')[2]))
const post = computed(() => posts.find((p) => p.id === postId.value))
const postAuthor = computed(() => (post.value ? authors[post.value.author] : null))
const comments = ref([])
watchEffect(() => {
  if (path.value.startsWith('/post/')) comments.value = getComments(postId.value)
})
const draft = ref('')
function submitComment() {
  addComment(postId.value, draft.value)
  draft.value = ''
  comments.value = getComments(postId.value)
}

// Profile (sinks reachable via ?url / ?bio, no backend needed)
const profileAuthor = computed(() => {
  const a = authors[path.value.split('/')[2]]
  if (!a) return null
  return { ...a, website: query.value.get('url') || a.website, bio: query.value.get('bio') || a.bio }
})

// Compose
const composeHtml = ref('<h2>Draft</h2><p>Type some HTML…</p>')
const embedUrl = ref('')
// VULN[vue-csti] — the live preview compiles a user-controlled template at
// runtime. Vue's runtime-compiled render runs expressions in a with(_ctx)
// scope, so {{constructor.constructor('alert(1)')()}} escapes to script exec.
const tpl = ref('Hello {{ 1 + 1 }}')
const previewComp = computed(() => ({ template: `<div class="body">${tpl.value}</div>` }))
// Kept as data (not inline in the template) so the SFC parser doesn't try to
// evaluate the literal {{ }} as an interpolation.
const cstiHint = "{{constructor.constructor('alert(1)')()}}"
</script>

<template>
  <div class="app">
    <nav>
      <span class="brand">DevBlog · vue</span>
      <a href="#/">Home</a>
      <a href="#/compose">Compose</a>
      <a href="#/profile/ada">Profile</a>
    </nav>

    <div class="container">
      <!-- Home -->
      <div v-if="path === '/' || path === ''" class="layout">
        <main>
          <h1>Latest posts</h1>
          <div v-for="p in posts" :key="p.id" class="teaser">
            <a :href="`#/post/${p.id}`"><h2>{{ p.title }}</h2></a>
            <p class="byline">by {{ authors[p.author].name }}</p>
          </div>
        </main>
        <aside>
          <h3>Widget</h3>
          <component :is="widget" />
          <p class="hint">try <code>#/?widget=admin</code></p>
        </aside>
      </div>

      <!-- Post -->
      <article v-else-if="path.startsWith('/post/')">
        <template v-if="post">
          <h1>{{ post.title }}</h1>
          <p class="byline">by {{ postAuthor.name }} — <AuthorLink :author="postAuthor" /></p>
          <PostBody :html="post.body" />
          <section class="comments">
            <h3>Comments</h3>
            <p v-if="comments.length === 0" class="muted">No comments yet.</p>
            <PostBody v-for="(c, i) in comments" :key="i" cls="comment" :html="c.body" />
            <form @submit.prevent="submitComment">
              <textarea v-model="draft" placeholder="Add a comment (HTML allowed)…"></textarea>
              <button type="submit">Post comment</button>
            </form>
          </section>
        </template>
        <p v-else>Post not found.</p>
      </article>

      <!-- Compose -->
      <div v-else-if="path.startsWith('/compose')">
        <h1>Compose</h1>

        <label>Body (HTML)</label>
        <textarea v-model="composeHtml"></textarea>
        <h3>Live preview (v-html)</h3>
        <PostBody :html="composeHtml" />

        <label>Template preview (compiled)</label>
        <input v-model="tpl" />
        <component :is="previewComp" />
        <p class="hint">CSTI try: <code>{{ cstiHint }}</code></p>

        <label>Embed URL</label>
        <input v-model="embedUrl" placeholder="https://…" />
        <Embed :url="embedUrl" />
      </div>

      <!-- Profile -->
      <div v-else-if="path.startsWith('/profile/')">
        <template v-if="profileAuthor">
          <h1>{{ profileAuthor.name }}</h1>
          <PostBody :html="profileAuthor.bio" />
          <p><AuthorLink :author="profileAuthor" /></p>
          <p class="hint">try <code>#/profile/ada?url=javascript:alert(document.domain)</code></p>
        </template>
        <p v-else>No such author.</p>
      </div>
    </div>
  </div>
</template>
