// vms/frontend-str-react/src/App.jsx
import React, { useEffect, useState } from 'react'
import { posts, authors, getComments, addComment } from './data.js'
import { PostBody, AuthorLink, Embed, SpreadCard, Widget } from './components.jsx'

function useHashRoute() {
  const [hash, setHash] = useState(window.location.hash || '#/')
  useEffect(() => {
    const on = () => setHash(window.location.hash || '#/')
    window.addEventListener('hashchange', on)
    return () => window.removeEventListener('hashchange', on)
  }, [])
  return hash
}

function queryOf(hash) {
  const i = hash.indexOf('?')
  return new URLSearchParams(i >= 0 ? hash.slice(i + 1) : '')
}

function Nav() {
  return (
    <nav>
      <span className="brand">DevBlog · react</span>
      <a href="#/">Home</a>
      <a href="#/compose">Compose</a>
      <a href="#/profile/ada">Profile</a>
    </nav>
  )
}

function Home({ query }) {
  const widget = query.get('widget') || 'hello'
  return (
    <div className="layout">
      <main>
        <h1>Latest posts</h1>
        {posts.map((p) => (
          <div key={p.id} className="teaser">
            <a href={`#/post/${p.id}`}>
              <h2>{p.title}</h2>
            </a>
            <p className="byline">by {authors[p.author].name}</p>
          </div>
        ))}
      </main>
      <aside>
        <h3>Widget</h3>
        <Widget name={widget} />
        <p className="hint">
          try <code>#/?widget=admin</code>
        </p>
      </aside>
    </div>
  )
}

function Post({ id }) {
  const post = posts.find((p) => p.id === Number(id))
  const [comments, setComments] = useState(() => getComments(id))
  const [draft, setDraft] = useState('')
  if (!post) return <p>Post not found.</p>
  const author = authors[post.author]
  const submit = (e) => {
    e.preventDefault()
    addComment(id, draft)
    setComments(getComments(id))
    setDraft('')
  }
  return (
    <article>
      <h1>{post.title}</h1>
      <p className="byline">
        by {author.name} — <AuthorLink author={author} />
      </p>
      <PostBody html={post.body} />
      <section className="comments">
        <h3>Comments</h3>
        {comments.length === 0 && <p className="muted">No comments yet.</p>}
        {comments.map((c, i) => (
          <PostBody key={i} className="comment" html={c.body} />
        ))}
        <form onSubmit={submit}>
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="Add a comment (HTML allowed)…"
          />
          <button type="submit">Post comment</button>
        </form>
      </section>
    </article>
  )
}

function Compose() {
  const [html, setHtml] = useState('<h2>Draft</h2><p>Type some HTML…</p>')
  const [embed, setEmbed] = useState('')
  const [spread, setSpread] = useState('{"title":"hover me"}')
  let spreadProps = {}
  try {
    spreadProps = JSON.parse(spread)
  } catch {
    spreadProps = {}
  }
  return (
    <div>
      <h1>Compose</h1>

      <label>Body (HTML)</label>
      <textarea value={html} onChange={(e) => setHtml(e.target.value)} />
      <h3>Live preview</h3>
      <PostBody html={html} />

      <label>Embed URL</label>
      <input value={embed} onChange={(e) => setEmbed(e.target.value)} placeholder="https://…" />
      <Embed url={embed} />

      <label>Card attributes (JSON, spread onto a &lt;div&gt;)</label>
      <input value={spread} onChange={(e) => setSpread(e.target.value)} />
      <SpreadCard props={spreadProps} />
      <p className="hint">
        spread try:{' '}
        <code>{'{"dangerouslySetInnerHTML":{"__html":"<img src=x onerror=alert(1)>"}}'}</code>
      </p>
    </div>
  )
}

function Profile({ id, query }) {
  const author = authors[id]
  if (!author) return <p>No such author.</p>
  // Overridable from the query string so the URL / bio sinks are reachable
  // without a backend: #/profile/ada?url=javascript:alert(1)
  const a = {
    ...author,
    website: query.get('url') || author.website,
    bio: query.get('bio') || author.bio,
  }
  return (
    <div>
      <h1>{a.name}</h1>
      <PostBody html={a.bio} />
      <p>
        <AuthorLink author={a} />
      </p>
      <p className="hint">
        try <code>#/profile/ada?url=javascript:alert(document.domain)</code>
      </p>
    </div>
  )
}

export default function App() {
  const hash = useHashRoute()
  const query = queryOf(hash)
  const path = hash.replace(/^#/, '').split('?')[0]

  let view
  if (path.startsWith('/post/')) view = <Post id={path.split('/')[2]} />
  else if (path.startsWith('/compose')) view = <Compose />
  else if (path.startsWith('/profile/')) view = <Profile id={path.split('/')[2]} query={query} />
  else view = <Home query={query} />

  return (
    <div className="app">
      <Nav />
      <div className="container">{view}</div>
    </div>
  )
}

// vms/frontend-str-vue/src/App.vue
<script setup>
import { ref, computed, watchEffect, onMounted, onUnmounted } from 'vue'
import { posts, authors, getComments, addComment } from './data.js'
import { PostBody, AuthorLink, Embed, widgets } from './components.js'

const hash = ref(window.location.hash || '#/')
const onHash = () => { hash.value = window.location.hash || '#/' }
onMounted(() => window.addEventListener('hashchange', onHash))
onUnmounted(() => window.removeEventListener('hashchange', onHash))

const query = computed(() => {
  const i = hash.value.indexOf('?')
  return new URLSearchParams(i >= 0 ? hash.value.slice(i + 1) : '')
})
const path = computed(() => hash.value.replace(/^#/, '').split('?')[0])

// Home / widget
const widget = computed(() => widgets[query.value.get('widget')] || widgets.hello)

// Post view
const postId = computed(() => Number(path.value.split('/')[2]))
const post = computed(() => posts.find((p) => p.id === postId.value))
const postAuthor = computed(() => (post.value ? authors[post.value.author] : null))
const comments = ref([])
watchEffect(() => {
  if (path.value.startsWith('/post/')) comments.value = getComments(postId.value)
})
const draft = ref('')
function submitComment() {
  addComment(postId.value, draft.value)
  draft.value = ''
  comments.value = getComments(postId.value)
}

// Profile (sinks reachable via ?url / ?bio, no backend needed)
const profileAuthor = computed(() => {
  const a = authors[path.value.split('/')[2]]
  if (!a) return null
  return { ...a, website: query.value.get('url') || a.website, bio: query.value.get('bio') || a.bio }
})

// Compose
const composeHtml = ref('<h2>Draft</h2><p>Type some HTML…</p>')
const embedUrl = ref('')
// VULN[vue-csti] — the live preview compiles a user-controlled template at
// runtime. Vue's runtime-compiled render runs expressions in a with(_ctx)
// scope, so {{constructor.constructor('alert(1)')()}} escapes to script exec.
const tpl = ref('Hello {{ 1 + 1 }}')
const previewComp = computed(() => ({ template: `<div class="body">${tpl.value}</div>` }))
// Kept as data (not inline in the template) so the SFC parser doesn't try to
// evaluate the literal {{ }} as an interpolation.
const cstiHint = "{{constructor.constructor('alert(1)')()}}"
</script>

<template>
  <div class="app">
    <nav>
      <span class="brand">DevBlog · vue</span>
      <a href="#/">Home</a>
      <a href="#/compose">Compose</a>
      <a href="#/profile/ada">Profile</a>
    </nav>

    <div class="container">
      <!-- Home -->
      <div v-if="path === '/' || path === ''" class="layout">
        <main>
          <h1>Latest posts</h1>
          <div v-for="p in posts" :key="p.id" class="teaser">
            <a :href="`#/post/${p.id}`"><h2>{{ p.title }}</h2></a>
            <p class="byline">by {{ authors[p.author].name }}</p>
          </div>
        </main>
        <aside>
          <h3>Widget</h3>
          <component :is="widget" />
          <p class="hint">try <code>#/?widget=admin</code></p>
        </aside>
      </div>

      <!-- Post -->
      <article v-else-if="path.startsWith('/post/')">
        <template v-if="post">
          <h1>{{ post.title }}</h1>
          <p class="byline">by {{ postAuthor.name }} — <AuthorLink :author="postAuthor" /></p>
          <PostBody :html="post.body" />
          <section class="comments">
            <h3>Comments</h3>
            <p v-if="comments.length === 0" class="muted">No comments yet.</p>
            <PostBody v-for="(c, i) in comments" :key="i" cls="comment" :html="c.body" />
            <form @submit.prevent="submitComment">
              <textarea v-model="draft" placeholder="Add a comment (HTML allowed)…"></textarea>
              <button type="submit">Post comment</button>
            </form>
          </section>
        </template>
        <p v-else>Post not found.</p>
      </article>

      <!-- Compose -->
      <div v-else-if="path.startsWith('/compose')">
        <h1>Compose</h1>

        <label>Body (HTML)</label>
        <textarea v-model="composeHtml"></textarea>
        <h3>Live preview (v-html)</h3>
        <PostBody :html="composeHtml" />

        <label>Template preview (compiled)</label>
        <input v-model="tpl" />
        <component :is="previewComp" />
        <p class="hint">CSTI try: <code>{{ cstiHint }}</code></p>

        <label>Embed URL</label>
        <input v-model="embedUrl" placeholder="https://…" />
        <Embed :url="embedUrl" />
      </div>

      <!-- Profile -->
      <div v-else-if="path.startsWith('/profile/')">
        <template v-if="profileAuthor">
          <h1>{{ profileAuthor.name }}</h1>
          <PostBody :html="profileAuthor.bio" />
          <p><AuthorLink :author="profileAuthor" /></p>
          <p class="hint">try <code>#/profile/ada?url=javascript:alert(document.domain)</code></p>
        </template>
        <p v-else>No such author.</p>
      </div>
    </div>
  </div>
</template>
